name: .NET BOT D1 BUILD InetumT

on:
  push:
    branches:
      - 'master'
    paths:
      - './src/**'
      - .github/workflows/echobot-build-InetumT.yml

  pull_request:
    branches:
      - 'master'
    paths:
      - './src/**'
      - .github/workflows/echobot-build-InetumT.yml

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  # /home/runner/work/publish
  Base:        publish
  Component:   EchoBot
  BuildName:   0.1.${{ github.run_number }}
  Environment: D1
  OrgName:     InetumT
  Location:    centralus

jobs:
  build:
    environment: Test

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Run pwsh
      shell: pwsh
      run: | 
        echo "${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/"
    - uses: nuget/setup-nuget@v1
    - run: nuget restore src\EchoBot.sln
    
    - name: Create Build Directory
      run: mkdir ${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
    
    - name: Build Solution
      run: |
        msbuild.exe src\EchoBot.sln /nologo /p:platform="x64" /p:OutDir=${{ github.workspace }}/${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/
        
    - name: Run pwsh
      shell: pwsh
      run: | 
        Get-ChildItem -Path ${{ github.workspace }}\${{ env.Base }}\${{ env.Component }}\${{ env.BuildName }}\
        echo ${{ github.workspace }}
    
    - name: Login via Az module
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: G1_RG_UploadArtifacts_to_Blob
      uses: Azure/powershell@v2
      with:
        inlineScript: |
          Get-ChildItem -Path  ./${{ env.Base }}/${{ env.Component }}/${{ env.BuildName }}/ # -Recurse

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = $env:Base
            OrgName       = $env:OrgName
            Location      = $env:location
          }
          & ./ADF/release-az/Sync-AzBuildComponent.ps1 @Params
        azPSVersion: latest

    - name: G1_RG_UpdateBuildMeta_to_Blob
      uses: Azure/powershell@v2
      with:
        inlineScript: |
          echo $home
          ls $home

          $Params = @{
            App           = 'BOT'
            BuildName     = $env:BuildName
            ComponentName = $env:Component
            BasePath      = $env:Base
            OrgName       = $env:OrgName
            Location      = $env:location
            Environment   = $env:Environment
          }
          & ./ADF/release-az/Update-AzBuildMetaData.ps1 @Params
        azPSVersion: latest



